upstream data_processor {
    server data-processor:8000;
    # Com replicas o Docker resolve automaticamente
    # para as múltiplas instâncias pelo nome do serviço
}

upstream results_manager {
    server results-manager:8001;
}

server {
    listen 80;

    # Rotas do data-processor
    location /data/ {
        proxy_pass http://data_processor/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Rotas do results-manager
    location /results/ {
        proxy_pass http://results_manager/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Health check do próprio Nginx
    location /health {
        return 200 '{"status": "nginx ok"}';
        add_header Content-Type application/json;
    }

    location /dashboard/ {
        proxy_pass http://web-interface:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}   